### ISSUE TITLE
Example sketches Queue.ino and Stack.ino usage reversed?

### ISSUE THREAD

**Issue by alw1746** [rlogiacco/CircularBuffer#25]
Queue.ino is described as a FIFO example but it calls push/pop which are stack operations. Conversely Stack.ino calls push/shift methods which looks like LIFO queue ops. Pls confirm if they are meant to be that way.

**Comment by rlogiacco** [comment]
Actually the operations are named after the common _array operations_, not after the stack or queue ones (otherwise I would have used `enqueue` and `dequeue`), but your point is spot on, so thanks!

I will alter the examples as follows:

 * `Queue.ino` will use `unshift` and `pop`
* `Stack.ino` is going to use `push` and `pop`

**Comment by rlogiacco** [comment]
Thank you for pointing it out
