### ISSUE TITLE
Supertype to allow pointers to CircularBuffers of different sizes

### ISSUE THREAD

**Issue by sehrgut** [rlogiacco/CircularBuffer#35]
In my application, I'm using CircularBuffer to implement a queue the size of which is determined by a child class, which enqueues items to be consumed by a parent-class method. It would be useful if CircularBuffer<T,S> implemented a parent class ICircularBuffer<T>, allowing my parent class to hold a pointer to that type, while the size was managed by my child class (which knows S at compile-time).

Is this a feature you'd consider adding?

**Comment by rlogiacco** [comment]
I'm not sure why you can't achieve the same goal using composition rather than inheritance, anyways as the library strives for compactness I'm pretty sure the approach you suggest consumes a tiny bit more memory just to support a very specific requirement.
If you get your changes working in your own fork and the community proves me wrong regarding my _corner case_ statement we might have your changes integrated.
For now, I prefer to keep the library as simple and compact as possible.

Nonetheless, I wish to thank you very much for the suggestion and for using this project.

Regards,
   Roberto
